### ISSUE TITLE
Show decrypted contacts after decryption

### ISSUE THREAD

**Issue by lekoook** [CS2113-AY1819S1-W12-3/main#32]
Currently, opening an address book that was previously encrypted will display no contacts.

However, after decrypting in the same session, the contacts **do not** show up. Session has to be restarted to show the contacts again.

Request:
Refresh the contacts list after decryption.
Provide feedback (visual) to let the user know if address book is currently encrypted or not.

**Comment by lws803** [comment]
Also added that feature to passwordManager
