### ISSUE TITLE
Encrypting twice DELETES all contacts

### ISSUE THREAD

**Issue by lekoook** [CS2113-AY1819S1-W12-3/main#33]
Steps to recreate bug:
1. Encrypt address book with some contacts already in entry.
2. Reopen address book.
3. Add a new contact.
4. Encrypt address book again.
5. Reopen address book.
6. Decrypt address book.
7. Reopen address book.
8. All previous contacts except for the newly added one, is all **DELETED**.

Critical bug since it involves all data lost without any prompts to user.

**Comment by lws803** [comment]
Resolved withe error handling and throwing exceptions
